server:
  port: ${PORT:8081}

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/Auth_DB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgresql}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# 🔐 JWT CONFIG
jwt:
  secret: ${JWT_SECRET:mysecretkeymysecretkeymysecretkey12345}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}