server:
  port: ${PORT:8080}

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        # 🔥 Swagger Docs FIRST
        - id: auth-docs
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: provider-docs
          uri: lb://PROVIDER-SERVICE
          predicates:
            - Path=/providers/v3/api-docs/**
          filters:
            - StripPrefix=1

        # 🔐 AUTH SERVICE APIs
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # 🔐 PROVIDER SERVICE APIs
        - id: provider-service
          uri: lb://PROVIDER-SERVICE
          predicates:
            - Path=/providers/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

# 🔥 Swagger Aggregation
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: provider-service
        url: /providers/v3/api-docs

# 🔐 JWT CONFIG (from Render env)
jwt:
  secret: ${JWT_SECRET}